### ISSUE TITLE
Support poo as alias for accrocchio

### ISSUE THREAD

**Issue by daddinuz** [fcracker79/accrocchio#1]
Wuold be really cool something like this:

```python
from accrocchio.badge_of_shame import 💩

class SomeShittyCode(metaclass=💩):
    pass

with 💩:
    some_shitty_function()

@💩
def a_very_stinky_function():
    pass
```

so that one can count how many 💩s are present in the code. :smile:

**Comment by fcracker79** [comment]
Unfortunately, not all Unicode characters are supported in identifiers (see [this link](https://www.python.org/dev/peps/pep-3131/#specification-of-language-changes))
